# src/ui/pages/8_Alerts.py
"""Alerts page.

Displays real fraud alerts stored in PostgreSQL.
"""

import pandas as pd
import streamlit as st

from src.db.models import Alert, Prediction, Transaction
from src.db.session import SessionLocal
from src.logging.logger import get_logger
from src.security.auth import require_auth


logger = get_logger(__name__)

def _load_alerts(db, user_id: int | None, limit: int = 100):
    """Load recent alerts with prediction and transaction details."""
    query = (
        db.query(Alert, Prediction, Transaction)
        .join(
            Prediction,
            Alert.prediction_id == Prediction.id,
        )
        .join(
            Transaction,
            Prediction.transaction_id == Transaction.id,
        )
    )

    if user_id is not None:
        query = query.filter(Alert.user_id == user_id)

    return (
        query
        .order_by(Alert.created_at.desc())
        .limit(limit)
        .all()
    )

def _severity_label(risk_score: float) -> str:
    """Convert a risk score into a severity label."""
    if risk_score >= 90:
        return "Critical"
    if risk_score >= 80:
        return "High"
    if risk_score >= 60:
        return "Medium"
    return "Low"


def _render_alert_card(
    alert: Alert,
    prediction: Prediction,
    transaction: Transaction,
) -> None:
    """Render one alert card."""
    risk_score = float(alert.risk_score or 0.0)
    severity = _severity_label(risk_score)
    created_at = (
        alert.created_at.strftime("%Y-%m-%d %H:%M:%S")
        if alert.created_at
        else "Unknown"
    )

    transaction_id = transaction.id
    probability = float(prediction.fraud_probability or 0.0)
    category = prediction.fraud_category or "Unknown"
    reason = alert.reason or "High-risk transaction detected"
    explanation = prediction.explanation or "No explanation available."

    if severity == "Critical":
        st.error(
            f"🚨 {severity} Alert | Risk: {risk_score:.0f} | "
            f"Transaction ID: {transaction_id}"
        )
    elif severity == "High":
        st.warning(
            f"⚠️ {severity} Alert | Risk: {risk_score:.0f} | "
            f"Transaction ID: {transaction_id}"
        )
    else:
        st.info(
            f"ℹ️ {severity} Alert | Risk: {risk_score:.0f} | "
            f"Transaction ID: {transaction_id}"
        )

    detail_col1, detail_col2, detail_col3 = st.columns(3)

    detail_col1.metric(
        "Fraud Probability",
        f"{probability:.2%}",
    )
    detail_col2.metric(
        "Category",
        category,
    )
    detail_col3.metric(
        "Created At",
        created_at,
    )

    st.write(f"**Reason:** {reason}")

    with st.expander("View explanation and transaction details"):
        st.write(explanation)

        raw_data = (
            transaction.raw_data
            if isinstance(transaction.raw_data, dict)
            else {}
        )

        if raw_data:
            st.json(raw_data)
        else:
            st.info("No raw transaction data is available.")

    st.markdown("---")


def render():
    """Render the Alerts page."""
    require_auth()

    st.title("⚠️ Alerts")
    st.caption("Recent fraud alerts generated by PayShield AI.")

    db = SessionLocal()

    try:
        user_id = st.session_state.get("user_id")

        limit = st.selectbox(
            "Number of alerts to display",
            options=[10, 25, 50, 100],
            index=1,
        )

        records = _load_alerts(
            db,
            user_id=user_id,
            limit=limit,
        )

        if not records:
            st.info("No fraud alerts are available.")
            return

        alert_rows = []

        for alert, prediction, transaction in records:
            alert_rows.append(
                {
                    "alert_id": alert.id,
                    "created_at": alert.created_at,
                    "transaction_id": transaction.id,
                    "risk_score": float(alert.risk_score or 0.0),
                    "severity": _severity_label(
                        float(alert.risk_score or 0.0)
                    ),
                    "reason": alert.reason,
                    "fraud_probability": float(
                        prediction.fraud_probability or 0.0
                    ),
                    "fraud_category": (
                        prediction.fraud_category or "Unknown"
                    ),
                }
            )

        df_alerts = pd.DataFrame(alert_rows)

        total_alerts = len(df_alerts)
        critical_alerts = int(
            (df_alerts["severity"] == "Critical").sum()
        )
        high_alerts = int(
            (df_alerts["severity"] == "High").sum()
        )
        average_risk = float(
            df_alerts["risk_score"].mean()
        )

        metric_col1, metric_col2, metric_col3, metric_col4 = st.columns(4)

        metric_col1.metric(
            "Total Alerts",
            f"{total_alerts:,}",
        )
        metric_col2.metric(
            "Critical",
            f"{critical_alerts:,}",
        )
        metric_col3.metric(
            "High",
            f"{high_alerts:,}",
        )
        metric_col4.metric(
            "Average Risk",
            f"{average_risk:.2f}",
        )

        st.subheader("Alert Summary")

        st.dataframe(
            df_alerts[
                [
                    "created_at",
                    "transaction_id",
                    "risk_score",
                    "severity",
                    "reason",
                    "fraud_probability",
                    "fraud_category",
                ]
            ],
            use_container_width=True,
        )

        st.subheader("Alert Details")

        for alert, prediction, transaction in records:
            _render_alert_card(
                alert,
                prediction,
                transaction,
            )

        logger.info(
            "Rendered Alerts page with %d database alerts",
            len(records),
        )

    finally:
        db.close()