# src/ui/pages/fraud_monitoring.py
"""
Combined Fraud Monitoring page.

Provides two tabs:
1️⃣ Real‑Time Monitoring – shows the latest processed transactions with predictions.
2️⃣ Alerts – displays recent fraud alerts stored in PostgreSQL.

All authentication, database access, and model imports are retained from the original pages.
"""

import pandas as pd
import streamlit as st

from src.security.auth import require_auth
from src.db.session import SessionLocal
from src.db.models import Prediction, Transaction, Alert
from src.logging.logger import get_logger

logger = get_logger(__name__)


# ----------------------------------------------------------------------
# Helper: Real‑Time Monitoring (from 3_RealTimeMonitoring.py)
# ----------------------------------------------------------------------
def _render_real_time_monitoring() -> None:
    """Render the Real‑Time Monitoring tab."""
    st.title("📈 Real‑Time Monitoring")
    st.caption("Shows the latest processed transactions with predictions.")

    db = SessionLocal()
    try:
        recent = (
            db.query(Prediction, Transaction)
            .join(Transaction, Prediction.transaction_id == Transaction.id)
            .order_by(Prediction.created_at.desc())
            .limit(20)
            .all()
        )
        if recent:
            rows = []
            for pred, txn in recent:
                rows.append(
                    {
                        "time": pred.created_at,
                        "risk": pred.risk_score,
                        "prediction": "Fraud" if pred.prediction else "Legit",
                        "explanation": pred.explanation or "—",
                    }
                )
            df = pd.DataFrame(rows)
            st.dataframe(df)
        else:
            st.info("No transactions processed yet.")
    finally:
        db.close()


# ----------------------------------------------------------------------
# Helper: Alerts (from 8_Alerts.py)
# ----------------------------------------------------------------------
def _load_alerts(db, user_id: int | None, limit: int = 100):
    """Load recent alerts together with their predictions and transactions."""
    query = (
        db.query(Alert, Prediction, Transaction)
        .join(Prediction, Alert.prediction_id == Prediction.id)
        .join(Transaction, Prediction.transaction_id == Transaction.id)
    )
    if user_id is not None:
        query = query.filter(Alert.user_id == user_id)
    return (
        query.order_by(Alert.created_at.desc())
        .limit(limit)
        .all()
    )


def _severity_label(risk_score: float) -> str:
    """Convert a risk score into a severity label."""
    if risk_score >= 90:
        return "Critical"
    if risk_score >= 80:
        return "High"
    if risk_score >= 60:
        return "Medium"
    return "Low"


def _render_alert_card(alert: Alert, prediction: Prediction, transaction: Transaction) -> None:
    """Render a single alert card."""
    risk_score = float(alert.risk_score or 0.0)
    severity = _severity_label(risk_score)
    created_at = (
        alert.created_at.strftime("%Y-%m-%d %H:%M:%S")
        if alert.created_at
        else "Unknown"
    )
    transaction_id = transaction.id
    probability = float(prediction.fraud_probability or 0.0)
    category = prediction.fraud_category or "Unknown"
    reason = alert.reason or "High‑risk transaction detected"
    explanation = prediction.explanation or "No explanation available."

    # Header based on severity
    if severity == "Critical":
        st.error(f"🚨 {severity} Alert | Risk: {risk_score:.0f} | Transaction ID: {transaction_id}")
    elif severity == "High":
        st.warning(f"⚠️ {severity} Alert | Risk: {risk_score:.0f} | Transaction ID: {transaction_id}")
    else:
        st.info(f"ℹ️ {severity} Alert | Risk: {risk_score:.0f} | Transaction ID: {transaction_id}")

    # Metrics
    col1, col2, col3 = st.columns(3)
    col1.metric("Fraud Probability", f"{probability:.2%}")
    col2.metric("Category", category)
    col3.metric("Created At", created_at)

    st.write(f"**Reason:** {reason}")

    with st.expander("View explanation and transaction details"):
        st.write(explanation)
        raw_data = transaction.raw_data if isinstance(transaction.raw_data, dict) else {}
        if raw_data:
            st.json(raw_data)
        else:
            st.info("No raw transaction data is available.")
    st.markdown("---")


def _render_alerts() -> None:
    """Render the Alerts tab."""
    st.title("⚠️ Alerts")
    st.caption("Recent fraud alerts generated by PayShield AI.")

    db = SessionLocal()
    try:
        user_id = st.session_state.get("user_id")
        limit = st.selectbox(
            "Number of alerts to display",
            options=[10, 25, 50, 100],
            index=1,
        )

        records = _load_alerts(db, user_id=user_id, limit=limit)

        if not records:
            st.info("No fraud alerts are available.")
            return

        # Build a summary DataFrame
        alert_rows = []
        for alert, pred, txn in records:
            alert_rows.append(
                {
                    "alert_id": alert.id,
                    "created_at": alert.created_at,
                    "transaction_id": txn.id,
                    "risk_score": float(alert.risk_score or 0.0),
                    "severity": _severity_label(float(alert.risk_score or 0.0)),
                    "reason": alert.reason,
                    "fraud_probability": float(pred.fraud_probability or 0.0),
                    "fraud_category": pred.fraud_category or "Unknown",
                }
            )
        df_alerts = pd.DataFrame(alert_rows)

        # Metrics
        total_alerts = len(df_alerts)
        critical_alerts = int((df_alerts["severity"] == "Critical").sum())
        high_alerts = int((df_alerts["severity"] == "High").sum())
        average_risk = float(df_alerts["risk_score"].mean())

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Total Alerts", f"{total_alerts:,}")
        col2.metric("Critical", f"{critical_alerts:,}")
        col3.metric("High", f"{high_alerts:,}")
        col4.metric("Average Risk", f"{average_risk:.2f}")

        # Summary table
        st.subheader("Alert Summary")
        st.dataframe(
            df_alerts[
                [
                    "created_at",
                    "transaction_id",
                    "risk_score",
                    "severity",
                    "reason",
                    "fraud_probability",
                    "fraud_category",
                ]
            ],
            use_container_width=True,
        )

        # Detailed cards
        st.subheader("Alert Details")
        for alert, pred, txn in records:
            _render_alert_card(alert, pred, txn)

        logger.info("Rendered Alerts tab with %d alerts", total_alerts)
    finally:
        db.close()


# ----------------------------------------------------------------------
# Public entry point
# ----------------------------------------------------------------------
def render() -> None:
    """Render the combined Fraud Monitoring page with two tabs."""
    require_auth()
    st.title("🛡️ Fraud Monitoring")
    st.caption("Combined real‑time monitoring and alert view.")

    tab_monitor, tab_alerts = st.tabs(["Real‑Time Monitoring", "Alerts"])

    with tab_monitor:
        _render_real_time_monitoring()
    with tab_alerts:
        _render_alerts()